version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recordings
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql

  app:
    build: .
    container_name: go_app
    environment:
      DBUSER: user
      DBPASS: password
      DBHOST: db
      DBPORT: 3306
      DBNAME: recordings
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: [ "sh", "-c", "sleep 10 && go run main.go" ]

volumes:
  mysql_data:
